apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
spec:
  template:
    spec:
      containers:
        - name: silly-demo
          env: 
          - name: DB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: silly-demo-db
                key: endpoint
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: silly-demo-db
                key: port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: silly-demo-db
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: silly-demo-db
                key: password
          - name: DB_NAME
            value: silly-demo-db
